/**
 * AUTO-GENERATED by scripts/gen-ts-theme.cjs
 * Do not edit manually. Run: node scripts/gen-ts-theme.cjs
 */
export const ThemeTokens = {
  "spacing": {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "lg": 16
  },
  "corner": 6,
  "font": "GothamMedium",
  "colors": {
    "panel": "#222326",
    "background": "#191A1C",
    "border": "#3C3C3C",
    "accent": "#0091FF",
    "text": "#EBEBEB",
    "muted": "#A0A0A0",
    "success": "#00AA55",
    "warning": "#D28C00",
    "error": "#FF5F5F"
  }
} as const;
